title: Pratyush # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Azure Data Engineer
  <br>"Transforming large, unruly data sets into competitive advantages."<br>
  <a href="mailto:pravs.x@gmail.com">Mail</a>
  <br>
  <a href="https://www.linkedin.com/in/pratyush-vashistha/">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
