title: Pratyush Vashistha # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Azure Data Engineer
  <br>Azure Data Engineer | "Transforming large, unruly data sets into competitive advantages.<br>
  <a href="mailto:inbox.prats@gmail.com">inbox.prats@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/pratyush-vashistha/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/pravsact/">Github</a> 
theme: jekyll-theme-minimal
